/* Lightweight, clearly labelled product illustrations. No account or file access. */
(() => {
  'use strict';
  const page=document.body,reduce=matchMedia('(prefers-reduced-motion: reduce)'),toggle=document.querySelector('[data-motion-toggle]');
  let motionOff=reduce.matches;
  function motion(){document.documentElement.classList.toggle('l-motion-off',motionOff);page.classList.toggle('l-motion-off',motionOff);toggle.setAttribute('aria-pressed',String(motionOff));toggle.setAttribute('aria-label',toggle.dataset[motionOff?'play':'pause']);toggle.querySelector('span').textContent=toggle.dataset[motionOff?'play':'pause'];toggle.querySelector('path').setAttribute('d',motionOff?'M7 4l13 8-13 8V4Z':'M8 5v14M16 5v14');}
  toggle.addEventListener('click',()=>{motionOff=!motionOff;motion();});reduce.addEventListener('change',e=>{motionOff=e.matches;motion();});motion();
  if('IntersectionObserver' in window){page.classList.add('l-ready');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target);}}),{rootMargin:'0px 0px 80px 0px',threshold:.08});document.querySelectorAll('[data-reveal]').forEach(el=>observer.observe(el));}
  document.querySelector('[data-name-play]').addEventListener('click',()=>{if(motionOff)return;page.classList.remove('l-name-replay');requestAnimationFrame(()=>page.classList.add('l-name-replay'));setTimeout(()=>page.classList.remove('l-name-replay'),950);});
  if(matchMedia('(hover:hover) and (pointer:fine)').matches)document.querySelectorAll('[data-tilt]').forEach(el=>{el.addEventListener('pointermove',e=>{if(motionOff)return;const r=el.getBoundingClientRect();el.style.setProperty('--tilt-x',((.5-(e.clientY-r.top)/r.height)*4)+'deg');el.style.setProperty('--tilt-y',(((e.clientX-r.left)/r.width-.5)*5)+'deg');});el.addEventListener('pointerleave',()=>{el.style.setProperty('--tilt-x','0deg');el.style.setProperty('--tilt-y','0deg');});});
  const demo=document.querySelector('[data-demo]'),data=JSON.parse(document.getElementById('launch-demo-data').textContent),pt=demo.dataset.lang==='pt-BR',t=(en,br)=>pt?br:en;
  const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const intro=(title,body,controls,visual)=>{demo.innerHTML=`<div class="l-demo-grid"><div><h3>${title}</h3><p>${body}</p>${controls}</div><div class="l-demo-visual">${visual}</div></div>`;};
  const buttons=(labels)=>`<div class="l-demo-buttons">${labels.map((label,i)=>`<button type="button" data-action="${i}">${label}</button>`).join('')}</div>`;
  const on=(selector,fn,event='click')=>demo.querySelector(selector).addEventListener(event,fn);
  switch(demo.dataset.demo){
    case 'gift': {
      const ideas=[['A weekend sketchbook','Um caderno de desenhos'],['A coffee tasting kit','Um kit de degustação de café'],['A trail picnic set','Um kit de piquenique']];
      intro(t('Make it about them.','Pense em quem vai receber.'),t('Choose an interest. Turn a small clue into a thoughtful gift idea.','Escolha um interesse e transforme uma pequena pista em uma ideia de presente.'),`<label for="gift-interest">${t('Their favorite thing','O que a pessoa gosta')}</label><select id="gift-interest"><option>${t('Art & creativity','Arte e criatividade')}</option><option>${t('Coffee rituals','Rituais de café')}</option><option>${t('The great outdoors','Passeios ao ar livre')}</option></select>${buttons([t('Save this idea','Salvar esta ideia')])}`,`<span class="l-demo-symbol" aria-hidden="true">✳</span><p>${t('An idea for someone special','Uma ideia para alguém especial')}</p><h4 data-gift-title></h4><p class="l-result" role="status"></p><p class="l-demo-caption">${t('Example gift ideas, not live AI recommendations.','Ideias de exemplo, não recomendações de IA ao vivo.')}</p>`);
      const update=()=>{demo.querySelector('[data-gift-title]').textContent=t(...ideas[demo.querySelector('select').selectedIndex]);demo.querySelector('[role=status]').textContent='';demo.querySelector('button').textContent=t('Save this idea','Salvar esta ideia');};on('select',update,'change');update();on('button',()=>{demo.querySelector('[role=status]').textContent=t('Added to your example list.','Adicionado à lista de exemplo.');demo.querySelector('button').textContent=t('Saved ✓','Salvo ✓');});break;
    }
    case 'flashcard': {
      const cards=[['What is active recall?','O que é recordação ativa?','Retrieving an answer from memory, before checking your notes.','Buscar a resposta na memória antes de consultar suas anotações.'],['What is spaced repetition?','O que é repetição espaçada?','Revisiting material at intervals instead of studying it all at once.','Revisar o conteúdo em intervalos em vez de estudar tudo de uma vez.'],['Why try a practice quiz?','Por que fazer um quiz?','To find what you remember and what needs another look.','Para descobrir o que você lembra e o que precisa revisar.']];let index=0,revealed=false;
      intro(t('A quick moment of recall.','Uma pausa para lembrar.'),t('Read the question. Think of an answer. Flip the card to check it.','Leia a pergunta. Pense na resposta. Vire o cartão para conferir.'),buttons([t('Reveal answer','Ver resposta'),t('Next card','Próximo cartão')]),'<div class="l-flash"><p data-progress></p><h4 data-question></h4><p data-answer hidden></p></div>');
      const draw=()=>{const card=cards[index];demo.querySelector('[data-progress]').textContent=`${index+1} / ${cards.length}`;demo.querySelector('[data-question]').textContent=t(card[0],card[1]);demo.querySelector('[data-answer]').textContent=t(card[2],card[3]);demo.querySelector('[data-answer]').hidden=!revealed;demo.querySelector('.l-flash').dataset.revealed=revealed;demo.querySelector('[data-action="0"]').textContent=revealed?t('Show question','Ver pergunta'):t('Reveal answer','Ver resposta');};draw();on('[data-action="0"]',()=>{revealed=!revealed;draw();});on('[data-action="1"]',()=>{index=(index+1)%cards.length;revealed=false;draw();});break;
    }
    case 'baby': {
      let entries=[{name:t('Feeding','Mamadeira'),time:'09:10'},{name:t('Nap','Soneca'),time:'10:00'}];
      intro(t('One little moment at a time.','Um momento de cada vez.'),t('Add a sample care event and see the day become easier to follow.','Adicione um cuidado de exemplo e acompanhe a rotina do dia.'),buttons([t('Log a feed','Registrar alimentação'),t('Log a nap','Registrar soneca'),t('Log a diaper','Registrar troca')]),`<p>${t('Today’s example timeline','Linha do tempo de exemplo')}</p><ul class="l-log" aria-live="polite"></ul><p class="l-demo-caption">${t('Fictional routine. No sleep or health recommendations.','Rotina fictícia, sem recomendações de saúde ou sono.')}</p>`);
      const draw=()=>demo.querySelector('ul').innerHTML=entries.map(e=>`<li><span>${e.name}</span><time>${e.time}</time></li>`).join('');draw();demo.querySelectorAll('button').forEach((b,i)=>b.addEventListener('click',()=>{entries.push({name:[t('Feeding','Alimentação'),t('Nap','Soneca'),t('Diaper','Troca de fralda')][i],time:new Intl.DateTimeFormat(pt?'pt-BR':'en-GB',{hour:'2-digit',minute:'2-digit'}).format(new Date())});entries=entries.slice(-4);draw();}));break;
    }
    case 'orbit': {
      intro(t('Find your orbit.','Encontre sua órbita.'),t('Change the orbit size, then send the little explorer around the planet.','Mude o tamanho da órbita e envie o explorador ao redor do planeta.'),`<label for="orbit-radius">${t('Orbit size','Tamanho da órbita')}</label><input id="orbit-radius" type="range" min="85" max="165" value="125">${buttons([t('Start orbit','Iniciar órbita')])}<p class="l-demo-caption">${t('A playful browser illustration. Discover the actual game below.','Uma ilustração divertida no navegador. Veja o jogo real abaixo.')}</p>`,`<svg class="l-orbit-demo" viewBox="0 0 400 400" aria-label="${t('Planet and an adjustable orbit','Planeta e órbita ajustável')}"><circle cx="200" cy="200" r="57" fill="var(--accent)"/><path d="M151 192q25-32 62-15t40 13M152 220q40 25 93-7" fill="none" stroke="var(--paper)" opacity=".4" stroke-width="9"/><circle data-orbit cx="200" cy="200" r="125" fill="none" stroke="var(--line)" stroke-width="2" stroke-dasharray="5 8"/><g class="l-satellite"><g data-ship transform="translate(325 200)"><path d="M-12 10 0-20 12 10 0 4Z" fill="var(--ink)"/><circle cy="-3" r="4" fill="var(--paper)"/></g></g><circle cx="57" cy="50" r="2" fill="var(--ink)"/><circle cx="330" cy="57" r="3" fill="var(--ink)"/><circle cx="355" cy="320" r="2" fill="var(--ink)"/></svg>`);
      on('input',()=>{const r=Number(demo.querySelector('input').value);demo.querySelector('[data-orbit]').setAttribute('r',r);demo.querySelector('[data-ship]').setAttribute('transform',`translate(${200+r} 200)`);demo.querySelector('svg').style.setProperty('--orbit-speed',r/10+'s');},'input');on('button',()=>{const svg=demo.querySelector('svg'),running=svg.dataset.running!=='true';svg.dataset.running=running;demo.querySelector('button').textContent=running?t('Pause orbit','Pausar órbita'):t('Start orbit','Iniciar órbita');});break;
    }
    case 'memories': {
      const names=[['Family at the beach','Família na praia'],['Baking together','Cozinhando juntos'],['A birthday together','Aniversário em família'],['A sunny picnic','Um piquenique'],['Our little companion','Nosso companheiro'],['A day in the garden','Um dia no jardim'],['A lake to remember','Um lago para lembrar'],['A city worth exploring','Uma cidade para explorar']];
      intro(t('A few moments worth keeping.','Momentos que merecem ficar.'),t('Move through a little timeline of family, pets and travel.','Passe por uma pequena linha do tempo de família, pets e viagens.'),`<label for="memory-position">${t('Explore the timeline','Explore a linha do tempo')}</label><input id="memory-position" type="range" min="0" max="${data.demo_photos.length-1}" value="0"><p class="l-demo-caption">${t('Fictional photo fixtures, not a customer’s family.','Fotos fictícias, não de uma família de clientes.')}</p>`,`<img class="l-memory-img" alt=""><h4 data-memory-title></h4><p data-memory-date></p>`);
      const draw=()=>{const n=Number(demo.querySelector('input').value),img=demo.querySelector('img');img.src=data.demo_photos[n].src;img.alt=t(...names[n]);demo.querySelector('[data-memory-title]').textContent=t(...names[n]);demo.querySelector('[data-memory-date]').textContent=`${n+1} / ${names.length}`;};on('input',draw,'input');draw();break;
    }
    case 'renewals': {
      const items=[[t('Music','Música'),9.99],[t('Cloud storage','Armazenamento'),2.99],[t('Video','Vídeo'),12.99]],money=new Intl.NumberFormat(pt?'pt-BR':'en-US',{style:'currency',currency:'USD'});
      intro(t('See the small costs add up.','Veja os pequenos custos somarem.'),t('Choose which example subscriptions to keep. Compare the monthly and yearly totals.','Escolha as assinaturas fictícias que deseja manter. Compare os totais mensais e anuais.'),items.map((v,i)=>`<label class="l-demo-option"><input type="checkbox" checked data-cost="${v[1]}"><span>${v[0]} · ${money.format(v[1])}</span></label>`).join(''),`<p>${t('Monthly total','Total mensal')}</p><div class="l-total" data-month></div><p class="l-result" data-year role="status"></p><p class="l-demo-caption">${t('Illustrative USD prices. No connection to your subscriptions.','Valores fictícios em USD, sem conexão com suas assinaturas.')}</p>`);
      const draw=()=>{let total=0;demo.querySelectorAll('input:checked').forEach(i=>total+=Number(i.dataset.cost));demo.querySelector('[data-month]').textContent=money.format(total);demo.querySelector('[data-year]').textContent=money.format(total*12)+' '+t('per year','por ano');};demo.querySelectorAll('input').forEach(i=>i.addEventListener('change',draw));draw();break;
    }
    case 'knock': {
      intro(t('A reminder you can notice.','Um lembrete que dá para perceber.'),t('Try how a clear, visible meeting reminder can bring you back from deep focus.','Veja como um lembrete claro e visível pode ajudar a sair do foco intenso.'),buttons([t('Show the reminder','Mostrar lembrete'),t('Reset','Recomeçar')]),`<div class="l-knock-visual"><span class="l-demo-symbol" aria-hidden="true">↗</span><h4>${t('Deep focus','Foco intenso')}</h4><p role="status">${t('Your next meeting is on the example calendar.','Sua próxima reunião está no calendário de exemplo.')}</p></div>`);
      on('[data-action="0"]',()=>{const v=demo.querySelector('.l-knock-visual');v.dataset.active=true;v.querySelector('h4').textContent=t('Design review · now','Revisão de design · agora');v.querySelector('[role=status]').textContent=t('Time to switch from your task to your meeting.','Hora de sair da tarefa e entrar na reunião.');});on('[data-action="1"]',()=>{const v=demo.querySelector('.l-knock-visual');v.dataset.active=false;v.querySelector('h4').textContent=t('Deep focus','Foco intenso');v.querySelector('[role=status]').textContent=t('Your next meeting is on the example calendar.','Sua próxima reunião está no calendário de exemplo.');});break;
    }
    case 'branches': {
      const branches=['main','feature/design','fix/navigation'];
      intro(t('Follow a branch.','Acompanhe uma branch.'),t('Select a sample branch and see its place in the project’s history.','Selecione uma branch de exemplo e veja seu lugar no histórico do projeto.'),`<div class="l-demo-buttons">${branches.map((n,i)=>`<button class="l-choice" aria-pressed="${i===0}" type="button" data-branch="${i}">${n}</button>`).join('')}</div>`,`<svg class="l-branch-map" viewBox="0 0 350 180" aria-hidden="true"><path d="M30 145H320M100 145Q100 50 170 50H280M200 145Q200 95 265 95H320"/><circle cx="280" cy="145" r="9" data-node="0"/><circle cx="280" cy="50" r="9" data-node="1"/><circle cx="320" cy="95" r="9" data-node="2"/></svg><h4 data-branch-title></h4><p role="status"></p>`);
      const draw=n=>{demo.querySelector('[data-branch-title]').textContent=branches[n];demo.querySelector('[role=status]').textContent=[t('The shared starting point.','O ponto de partida compartilhado.'),t('A separate space to explore the design.','Um espaço separado para explorar o design.'),t('A focused fix before bringing it back.','Uma correção focada antes de integrar.')][n];demo.querySelectorAll('[data-node]').forEach((e,i)=>e.classList.toggle('selected',i===n));demo.querySelectorAll('[data-branch]').forEach((e,i)=>e.setAttribute('aria-pressed',String(i===n)));};draw(0);demo.querySelectorAll('[data-branch]').forEach((e,i)=>e.addEventListener('click',()=>draw(i)));break;
    }
    case 'clean': {
      const names=[t('Old build cache','Cache antigo de builds'),t('Archived logs','Logs arquivados'),t('Temporary downloads','Downloads temporários')],sizes=[2.4,.6,1.2];
      intro(t('Choose before you clean.','Escolha antes de limpar.'),t('Review an example selection. Clear the sample items and see the space change.','Revise uma seleção de exemplo. Limpe os itens fictícios e veja o espaço mudar.'),names.map((name,i)=>`<label class="l-demo-option"><input type="checkbox" checked data-size="${sizes[i]}"><span>${name} · ${sizes[i]} GB</span></label>`).join('')+buttons([t('Clear sample selection','Limpar seleção fictícia'),t('Reset sample','Recomeçar')]),`<p>${t('Selected sample space','Espaço fictício selecionado')}</p><div class="l-total" data-size-total></div><p class="l-result" role="status"></p><p class="l-demo-caption">${t('No files are scanned or deleted.','Nenhum arquivo é analisado ou excluído.')}</p>`);
      const draw=()=>{let total=0;demo.querySelectorAll('input:checked').forEach(e=>total+=Number(e.dataset.size));demo.querySelector('[data-size-total]').textContent=total.toFixed(1)+' GB';};draw();demo.querySelectorAll('input').forEach(e=>e.addEventListener('change',draw));on('[data-action="0"]',()=>{const total=demo.querySelector('[data-size-total]').textContent;demo.querySelectorAll('input:checked').forEach(e=>{e.checked=false;e.disabled=true;});demo.querySelector('[role=status]').textContent=t('Sample cleared: ','Exemplo limpo: ')+total;draw();});on('[data-action="1"]',()=>{demo.querySelectorAll('input').forEach(e=>{e.checked=true;e.disabled=false;});demo.querySelector('[role=status]').textContent='';draw();});break;
    }
    case 'countdown': {
      const initial=new Date();initial.setDate(initial.getDate()+30);const value=[initial.getFullYear(),String(initial.getMonth()+1).padStart(2,'0'),String(initial.getDate()).padStart(2,'0')].join('-');
      intro(t('Give a good day a date.','Dê uma data a um dia especial.'),t('Pick a date and see how close your next good thing is.','Escolha uma data e veja quanto falta para o próximo momento especial.'),`<label for="countdown-date">${t('The day you’re waiting for','O dia que você está esperando')}</label><input id="countdown-date" type="date" value="${value}">`,`<span class="l-demo-symbol" aria-hidden="true">✳</span><div class="l-total" data-days></div><p class="l-result" role="status"></p>`);
      const draw=()=>{const raw=demo.querySelector('input').value;if(!raw){demo.querySelector('[data-days]').textContent='—';return;}const today=new Date();today.setHours(0,0,0,0);const date=new Date(raw+'T00:00:00'),days=Math.round((date-today)/86400000);demo.querySelector('[data-days]').textContent=Math.abs(days);demo.querySelector('[role=status]').textContent=days===0?t('Today is the day.','O dia chegou.'):days>0?t('days to look forward to','dias para esperar'):t('days since that moment','dias desde esse momento');};on('input',draw,'input');draw();break;
    }
    case 'card': {
      intro(t('A few words can make a day.','Algumas palavras mudam o dia.'),t('Write a small note and open your example card.','Escreva uma pequena mensagem e abra seu cartão de exemplo.'),`<label for="card-name">${t('For','Para')}</label><input id="card-name" maxlength="35" value="Alex"><label for="card-message">${t('Your message','Sua mensagem')}</label><textarea id="card-message" maxlength="180" rows="3">${t('Here’s to all the good things ahead.','Que venham muitos momentos bons.')}</textarea>${buttons([t('Open the card','Abrir o cartão')])}`,`<div class="l-postcard"><span class="l-demo-symbol" aria-hidden="true">✳</span><h4 data-card-name></h4><p data-card-message hidden></p></div>`);
      const draw=()=>{demo.querySelector('[data-card-name]').textContent=t('For ','Para ')+demo.querySelector('input').value;demo.querySelector('[data-card-message]').textContent=demo.querySelector('textarea').value;};on('input',draw,'input');on('textarea',draw,'input');draw();on('button',()=>{const card=demo.querySelector('.l-postcard'),opened=card.dataset.open!=='true';card.dataset.open=opened;demo.querySelector('[data-card-message]').hidden=!opened;demo.querySelector('button').textContent=opened?t('Close the card','Fechar o cartão'):t('Open the card','Abrir o cartão');});break;
    }
    case 'toys': {
      intro(t('A little paper play.','Uma pequena brincadeira de papel.'),t('Tap a paper friend and watch it move. A gentle taste of TumTum’s world.','Toque em um amigo de papel e veja ele se mexer. Um pedacinho tranquilo do mundo do TumTum.'),`<p class="l-demo-caption">${t('Browser illustration using original TumTum assets.','Ilustração no navegador com assets originais do TumTum.')}</p>`,`<div class="l-toy-stage">${data.props.slice(0,2).map((p,i)=>`<button type="button" class="l-toy" aria-label="${t('Move paper friend','Mover amigo de papel')} ${i+1}"><img src="${esc(p.src)}" alt=""></button>`).join('')}</div>`);
      demo.querySelectorAll('.l-toy').forEach(e=>e.addEventListener('click',()=>{if(motionOff)return;e.classList.remove('is-playing');requestAnimationFrame(()=>e.classList.add('is-playing'));setTimeout(()=>e.classList.remove('is-playing'),1050);}));break;
    }
  }
})();
