site: Magic Lab Solutions

url: https://magiclabsolutions.com
baseurl:

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /apps/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      featured_image: "/images/social.jpg"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

include:
  - ".well-known"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-polyglot

languages: ["en", "de", "es", "fr", "pt-BR", "ja", "ko", "zh-Hans"]
default_lang: "en"
parallel_localization: true
exclude_from_localization:
  - js
  - images
  - css
  - _sass
  - CNAME
  - googlee501f14b4b28a756.html
  - apps/brainfold/
  - apps/myrenewals/
  - apps/qramen/
  - zuzu/
  - battle/
  - invite/
  - "*.pdf"
  - "*.mp4"

paginate: 6
paginate_path: "/blog/page:num/"

include:
  - .well-known

