/** Render finished native-screen compositions. Standalone Apple artwork stays private. */
import fs from 'node:fs/promises';import path from 'node:path';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');const out=path.join(root,'docs/marketing/october-2026');
const {chromium}=createRequire(path.join(process.env.MAGICLAB_NODE_MODULES,'package.json'))('playwright');
const campaign=JSON.parse(await fs.readFile(path.join(out,'campaign.json'),'utf8'));const frames=JSON.parse(await fs.readFile(path.join(out,'device-framing.json'),'utf8')).frames;
const jobs=[];
const wanted=process.argv.slice(2);
for(const p of campaign.products){if(wanted.length&&!wanted.includes(p.slug))continue;if(p.frame)for(let i=0;i<p.screens.length;i++)jobs.push({screen:p.screens[i],frame:p.frame,target:path.join(out,'sources',p.slug,`framed-${i+1}.png`)});if(p.ipad_store)for(let i=0;i<p.ipad_store.screens.length;i++)jobs.push({screen:p.ipad_store.screens[i],frame:p.ipad_store.frame,target:path.join(out,'sources',p.slug,'ipad',`framed-${i+1}.png`)});}
if(!wanted.length||wanted.includes('brainfold'))for(const [device,dir] of [['iphone','apps/brainfold/screenshots/raw'],['ipad','apps/brainfold/screenshots/ipad/raw']])for(const f of await fs.readdir(path.join(root,dir)))if(/\.jpg$/.test(f))jobs.push({screen:'/'+dir+'/'+f,frame:frames.find(f=>f.hardware===device),target:path.join(root,dir.replace('/raw','/framed'),f.replace('.jpg','.webp'))});
const browser=await chromium.launch({headless:true,channel:'chrome'});const page=await browser.newPage();await page.goto('http://127.0.0.1:8766/docs/marketing/october-2026/art.html');
for(const job of jobs){const [fw,fh]=job.frame.dimensions;await page.setViewportSize({width:fw,height:fh});await page.evaluate(async({job,fw,fh})=>{document.body.innerHTML='<canvas id="composition"></canvas>';document.body.style.cssText='margin:0;background:transparent';document.documentElement.style.cssText='background:transparent';const c=document.querySelector('canvas');c.width=fw;c.height=fh;const ctx=c.getContext('2d');const cap=new Image(),bezel=new Image();cap.src=job.screen;bezel.src=job.frame.asset;await Promise.all([cap.decode(),bezel.decode()]);const [x,y,w,h]=job.frame.screen;ctx.save();ctx.beginPath();ctx.roundRect(x,y,w,h,job.frame.asset.includes('ipad')?42:150);ctx.clip();ctx.fillStyle='#f8f6ef';ctx.fillRect(x,y,w,h);const scale=Math.min(w/cap.width,h/cap.height);ctx.drawImage(cap,x+(w-cap.width*scale)/2,y+(h-cap.height*scale)/2,cap.width*scale,cap.height*scale);ctx.restore();ctx.drawImage(bezel,0,0,fw,fh);},{job,fw,fh});await fs.mkdir(path.dirname(job.target),{recursive:true});if(job.target.endsWith('.webp')){const data=await page.evaluate(()=>document.querySelector('canvas').toDataURL('image/webp',.9));await fs.writeFile(job.target,Buffer.from(data.split(',')[1],'base64'));}else await page.screenshot({path:job.target,omitBackground:true});}
await browser.close();console.log(`Rendered ${jobs.length} actual-device screen compositions.`);
